#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerunet
#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerAortaNet1
#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerMednext
#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerNnformer
#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerSegMamba
#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerSegResNet
python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerUNETR
#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerUXnet
python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerUMambaBot
python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerSwinUNETR
python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainerUxLSTMBot
#python ./nnunetv2/inference/predict_from_raw_data2a.py 0 nnUNetTrainer
#python ./nnunetv2/inference/predict_from_raw_data2b.py 0 nnUNetTrainerMaCNN2
