python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerNnformer
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerSegMamba
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerMednext
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerUxLSTMBot
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainer
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerUMambaBot
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerUNETR
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerSwinUNETR
python ./nnunetv2/inference/predict_from_raw_data12.py 0 nnUNetTrainerUXnet
